// neural_network_int8.cpp
// INT8 Quantized Neural Network Inference Engine Implementation
//
// Key optimizations:
// - INT8 weights (1 byte per weight vs 4 bytes FP32) = 4x memory reduction
// - INT8 operations (faster than FP32 on most hardware)
// - INT32 accumulators (avoids overflow during matrix multiply)
// - Static buffer allocation (no dynamic memory)

#include "neural_network_int8.h"

// Include the INT8 weights header (generated by export_int8_weights.py)
// This header contains:
// - INT8 weight arrays: conv1d_1_weight, fc_layers_0_weight, fc_layers_3_weight
// - Scale and zero_point for each layer
// - FP32 BatchNorm parameters
#include "model_weights_int8_s03.h"

// Math functions
#include <math.h>

// Constructor - initialize quantization parameters
NeuralNetworkInt8::NeuralNetworkInt8() {
    // Load quantization parameters from header
    // These are set by the weight export script

    // Conv1D params (use weight scale/zp from header)
    conv1d_weight_scale = conv1d_1_weight_scale;
    conv1d_weight_zp = conv1d_1_weight_zero_point;
    // Input quantization params (typical values, adjust based on training data range)
    conv1d_input_scale = 0.1f;  // Adjust based on IMU data range
    conv1d_input_zp = 0;
    // Output scale = input_scale * weight_scale (for requantization)
    conv1d_output_scale = conv1d_input_scale * conv1d_weight_scale;
    conv1d_output_zp = 0;

    // FC1 params
    fc1_weight_scale = fc_layers_0_weight_scale;
    fc1_weight_zp = fc_layers_0_weight_zero_point;
    fc1_input_scale = 0.1f;  // Adjust based on BN1 output range
    fc1_input_zp = 0;
    fc1_output_scale = fc1_input_scale * fc1_weight_scale;
    fc1_output_zp = 0;

    // FC2 params
    fc2_weight_scale = fc_layers_3_weight_scale;
    fc2_weight_zp = fc_layers_3_weight_zero_point;
    fc2_input_scale = 0.1f;  // Adjust based on BN2 output range
    fc2_input_zp = 0;
}

// Main prediction function
uint8_t NeuralNetworkInt8::predict(float* input) {
    float logits[NN_NUM_CLASSES];
    getLogits(input, logits);
    return argmax(logits, NN_NUM_CLASSES);
}

// Get raw logits (full forward pass)
void NeuralNetworkInt8::getLogits(float* input, float* logits) {
    // Forward pass through the network:
    // 1. Conv1D (FP32 input -> INT8 output)
    // 2. Dequantize -> BN1 (FP32) -> ReLU
    // 3. Quantize -> FC1 (INT8)
    // 4. Dequantize -> BN2 (FP32) -> ReLU
    // 5. Quantize -> FC2 (INT8) -> Dequantize
    // 6. Output logits (FP32)

    // Step 1: Conv1D
    computeConv1d(input, int8_buffer_200);

    // Step 2: Dequantize -> BN1 -> ReLU
    dequantize(int8_buffer_200, fp32_buffer_200, NN_FLATTEN_SIZE,
               conv1d_output_scale, conv1d_output_zp);
    computeBatchNorm1(fp32_buffer_200, fp32_buffer_200);
    applyReLU_FP32(fp32_buffer_200, NN_FLATTEN_SIZE);

    // Step 3: Quantize -> FC1
    quantize(fp32_buffer_200, int8_buffer_200, NN_FLATTEN_SIZE,
             fc1_input_scale, fc1_input_zp);
    computeFC1(int8_buffer_200, int8_buffer_42);

    // Step 4: Dequantize -> BN2 -> ReLU
    dequantize(int8_buffer_42, fp32_buffer_42, NN_FC1_OUTPUT,
               fc1_output_scale, fc1_output_zp);
    computeBatchNorm2(fp32_buffer_42, fp32_buffer_42);
    applyReLU_FP32(fp32_buffer_42, NN_FC1_OUTPUT);

    // Step 5: Quantize -> FC2 -> Dequantize
    quantize(fp32_buffer_42, int8_buffer_42, NN_FC1_OUTPUT,
             fc2_input_scale, fc2_input_zp);
    computeFC2(int8_buffer_42, logits);
}

// =====================================================
// Quantization Functions
// =====================================================

void NeuralNetworkInt8::quantize(float* input, int8_t* output, int size,
                                  float scale, int8_t zero_point) {
    for (int i = 0; i < size; i++) {
        // Quantize: q = round(x / scale) + zero_point
        int32_t q = (int32_t)roundf(input[i] / scale) + zero_point;
        // Clamp to INT8 range [-128, 127]
        if (q < -128) q = -128;
        if (q > 127) q = 127;
        output[i] = (int8_t)q;
    }
}

void NeuralNetworkInt8::dequantize(int8_t* input, float* output, int size,
                                    float scale, int8_t zero_point) {
    for (int i = 0; i < size; i++) {
        // Dequantize: x = (q - zero_point) * scale
        output[i] = ((float)(input[i] - zero_point)) * scale;
    }
}

// =====================================================
// Conv1D Layer (INT8)
// =====================================================

void NeuralNetworkInt8::computeConv1d(float* input, int8_t* output) {
    // Conv1D: (6, 60) -> (10, 20) -> flatten to (200,)
    // Kernel: (10, 6, 3), stride=3

    // First quantize input
    int8_t input_q[NN_INPUT_CHANNELS * NN_INPUT_LENGTH];
    for (int i = 0; i < NN_INPUT_CHANNELS * NN_INPUT_LENGTH; i++) {
        int32_t q = (int32_t)roundf(input[i] / conv1d_input_scale) + conv1d_input_zp;
        if (q < -128) q = -128;
        if (q > 127) q = 127;
        input_q[i] = (int8_t)q;
    }

    // Perform convolution
    int out_idx = 0;
    for (int k = 0; k < NN_NUM_KERNELS; k++) {
        for (int t = 0; t < NN_CONV_OUTPUT_LEN; t++) {
            int32_t acc = 0;  // INT32 accumulator

            // Dot product over (6 channels x 3 kernel elements)
            for (int c = 0; c < NN_INPUT_CHANNELS; c++) {
                for (int ks = 0; ks < NN_KERNEL_SIZE; ks++) {
                    int input_idx = c * NN_INPUT_LENGTH + t * NN_STRIDE + ks;
                    acc += (int32_t)input_q[input_idx] *
                           (int32_t)conv1d_1_weight[k][c][ks];
                }
            }

            // Requantize: scale accumulator back to INT8
            // acc is in (input_scale * weight_scale) domain
            // We want output in conv1d_output_scale domain
            float acc_float = (float)acc * conv1d_input_scale * conv1d_weight_scale;
            int32_t q_out = (int32_t)roundf(acc_float / conv1d_output_scale) + conv1d_output_zp;
            if (q_out < -128) q_out = -128;
            if (q_out > 127) q_out = 127;
            output[out_idx++] = (int8_t)q_out;
        }
    }
}

// =====================================================
// BatchNorm Layers (FP32)
// =====================================================

void NeuralNetworkInt8::computeBatchNorm1(float* input, float* output) {
    // BN: output = (input - running_mean) / sqrt(running_var + eps) * weight + bias
    for (int i = 0; i < NN_FLATTEN_SIZE; i++) {
        float normalized = (input[i] - bn1_running_mean[i]) /
                          sqrtf(bn1_running_var[i] + BN_EPS);
        output[i] = normalized * bn1_weight[i] + bn1_bias[i];
    }
}

void NeuralNetworkInt8::computeBatchNorm2(float* input, float* output) {
    for (int i = 0; i < NN_FC1_OUTPUT; i++) {
        float normalized = (input[i] - bn2_running_mean[i]) /
                          sqrtf(bn2_running_var[i] + BN_EPS);
        output[i] = normalized * bn2_weight[i] + bn2_bias[i];
    }
}

// =====================================================
// Fully Connected Layers (INT8)
// =====================================================

void NeuralNetworkInt8::computeFC1(int8_t* input, int8_t* output) {
    // FC1: (200,) -> (42,)
    for (int i = 0; i < NN_FC1_OUTPUT; i++) {
        int32_t acc = 0;
        for (int j = 0; j < NN_FLATTEN_SIZE; j++) {
            acc += (int32_t)input[j] * (int32_t)fc_layers_0_weight[i][j];
        }

        // Requantize
        float acc_float = (float)acc * fc1_input_scale * fc1_weight_scale;
        int32_t q_out = (int32_t)roundf(acc_float / fc1_output_scale) + fc1_output_zp;
        if (q_out < -128) q_out = -128;
        if (q_out > 127) q_out = 127;
        output[i] = (int8_t)q_out;
    }
}

void NeuralNetworkInt8::computeFC2(int8_t* input, float* output) {
    // FC2: (42,) -> (5,) with FP32 output (final logits)
    for (int i = 0; i < NN_NUM_CLASSES; i++) {
        int32_t acc = 0;
        for (int j = 0; j < NN_FC1_OUTPUT; j++) {
            acc += (int32_t)input[j] * (int32_t)fc_layers_3_weight[i][j];
        }

        // Dequantize to FP32 for final output
        output[i] = (float)acc * fc2_input_scale * fc2_weight_scale;
    }
}

// =====================================================
// Activation Functions
// =====================================================

void NeuralNetworkInt8::applyReLU_FP32(float* data, int size) {
    for (int i = 0; i < size; i++) {
        if (data[i] < 0.0f) {
            data[i] = 0.0f;
        }
    }
}

void NeuralNetworkInt8::applyReLU_INT8(int8_t* data, int size, int8_t zero_point) {
    // For INT8, ReLU means: max(x, zero_point)
    // Because zero_point represents 0.0 in quantized domain
    for (int i = 0; i < size; i++) {
        if (data[i] < zero_point) {
            data[i] = zero_point;
        }
    }
}

// =====================================================
// Argmax for Classification
// =====================================================

uint8_t NeuralNetworkInt8::argmax(float* logits, int size) {
    int max_idx = 0;
    float max_val = logits[0];
    for (int i = 1; i < size; i++) {
        if (logits[i] > max_val) {
            max_val = logits[i];
            max_idx = i;
        }
    }
    return (uint8_t)max_idx;
}

// INT8 matrix multiply helper (not currently used, for reference)
void NeuralNetworkInt8::matmul_int8(int8_t* input, const int8_t* weight,
                                     int32_t* output, int out_size, int in_size) {
    for (int i = 0; i < out_size; i++) {
        output[i] = 0;
        for (int j = 0; j < in_size; j++) {
            output[i] += (int32_t)input[j] * (int32_t)weight[i * in_size + j];
        }
    }
}
